/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jme3.gde.cinematic.gui;

import com.jme3.gde.cinematic.CinematicEditorManager;
import com.jme3.gde.cinematic.core.CinematicClip;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Rectangle;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.Scrollable;

/**
 *
 * @author MAYANK
 */
public class TimelineCanvas extends JPanel implements Scrollable{
    
    private List<Layer> entireLayerSpace;
    private List<Layer> visibleLayerSpace;
    private CinematicClip cinematicClip;
    /**
     * Creates new form TimelineMap
     */
    public TimelineCanvas(CinematicClip clip) {
        setLayout(new BoxLayout(this,BoxLayout.PAGE_AXIS));
        this.cinematicClip = clip;
        initCanvas();
        entireLayerSpace = new ArrayList<>();
        visibleLayerSpace = new ArrayList<>();
        //initComponents();
    }
    public void initCanvas()
    {
        Layer root = cinematicClip.getRoot();
        List<JPanel> layerSpace = GuiManager.getInstance().getChildrenLayerSpace(root);
        System.out.println("Size : " + layerSpace.size());
        for(JPanel layer: layerSpace)
            add(layer);
    }
    /**
     * adds the layer and all the children into a list form.
     * Lazy Loading of all the data
     * @param layer 
     */
    public void populateWithChildren(Layer layer) {
        entireLayerSpace = layer.findAllDescendants(layer);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    /**
     * Sets the size of the canvas holding the timeline chart paper.
     * @param width
     * @param height 
     */
    public void setTimelineDimension(int width,int height)
    {
        getBounds().height = height;
        getBounds().width = width;
    }
    
    @Override
    public Dimension getPreferredScrollableViewportSize() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public int getScrollableUnitIncrement(Rectangle visibleRect, int orientation, int direction) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public int getScrollableBlockIncrement(Rectangle visibleRect, int orientation, int direction) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public boolean getScrollableTracksViewportWidth() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public boolean getScrollableTracksViewportHeight() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    public static void main(String args[])
    {
        JFrame frame = new JFrame();
        CinematicClip clip = new CinematicClip("MyClip");
        CinematicEditorManager.getInstance().setCurrentClip(clip);
        Layer root = new Layer("MyClip-root",null);
        clip.setRoot(root);
        Layer child = new Layer("Child",root);
        Layer sibling = new Layer("Sibling",root);
        Layer grandChild = new Layer("GrandChild",child);
        TimelineCanvas canvas = new TimelineCanvas(clip);
        frame.add(canvas);
        frame.pack();
        frame.setVisible(true);
        
    }

    
}
